### ISSUE TITLE
Finalize All Icons for Publication - roundings

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus#298]

**Comment by soniakaukonen** [comment]
Feedback from .ai viewing

Modus-Account and Support-1021 and Modus-Account and Support-solid-1021
-web - close the small artifact in the lower part middle of the globe to simplify code

Modus-Actions and Navigation-1021 and Modus-Actions and Navigation-solid-1021
pause - line stroke is 3 px but could it be on grid to avoid pixelizing?
play - is the rounding of the arrow 2 px? Looks smaller
rotate, drag-horizontal and drag-vertical - make arrow heads' bottom on-grid to avoid blur
Do we really maintain the basic magnifier and remove/cancel, refresh/update under so many different names? Also bin? Should not it be done over keywords tags?
Toggle on and toggle off are other way round, no?
navigate -is there a reason that the circle is larger then other tokens? Only 1 px padding
pan (in solid) - arrows should have the bottom on grid
collapse (in solid) - arrow heads could be on grid

Modus-Computer Hardware and Assets-1021 and Modus-Computer Hardware and Assets-solid-1021
Some devices repeat within this file and with others (envelope), should it rather be tagged?
monitor - should rather the lower part be filled not the screen itself (consistent with tablets and mobiles)?

Modus-Documents and Reports-1021 and Modus-Documents and Reports-solid-1021
Fonts not converted to shapes!
text - still looks very massive and not natural. Should it be simply converted from a font?
Paper sheet under different names - rather keywords instead of doubles
As said earlier, drawings often don't look like a vertical A4, but horizontal with an index in the lower corner.  Many products really need this distinction

Modus-Folders and Files-1021 and Modus-Folders and Files-solid-1021
Many doubles, rather keywords?

Modus-Messages-1021
Error and warning the same? I think they should have distinction. Warning triangle with !  Warning happens before something critical happens, error thereafter.

TBC...

**Comment by soniakaukonen** [comment]
part 2

Modus-Modelling-1021 and Modus-Modelling-solid-1021
Sphere is larger than 2px padding

Modus-Presentations and View-1021 and Modus-Presentations and View-solid-1021
Chevron unified for outline and solid according to discussion
Alignment - compared to adobe those two versions lose their meaning. There always one is solid and one outlined to show the reference how alignment happens.
Skip is a double from another file, should it rather be added to keywords instead of a double?
walk-through - some unnecessary nodes on the tip of the left shoe / cut in a strange way
moon-phase and darkmode are a double. Also in the Status file another moon for other. Keywords instead.

Modus-Save-and-Share-1021 and Modus-Save-and-Share-solid-1021
Same add-on e.g. the arrow down or up has diffeent padding e.g. with the cloud, floppy or in the Folder ai with the folder. Make it consistent.

Modus-Status-1021 and Modus-Status-solid-1021
Cloud could be on grid on the even bottom side
---
